#!/bin/bash
#
# Delete .DS_Store and __MACOSX directories.
#

#function clear-macos-dir-metadata {
find "${@:-$PWD}" \( \
	-type f -name '.DS_Store' -o \
	-type d -name '__MACOSX' \
\) -print0 | xargs -0 rm -rf
#}
