#!/bin/bash
#
# Opens man pages in Preview.app.
#

#function manp {
local page
if (( $# > 0 )); then
	for page in "$@"; do
		man -t "$page" | open -f -a Preview
	done
else
	print 'What manual page would you like to read?' >&2
fi
#}
